= Sample application MicroProfile-Opentracing

This repository holds the sample application for illustrating the usage of MicroProfile-Opentracing with Thorntail, Quarkus and Wildfly, and is part of an article you find at https://www.gepardec.com/blog/
among other interesting articles.

== Description

This sample application implements a simple JEE application which uses MicroProfile-Opentracing to trace its rest resources as well as rest clients
and runs as a microservice with Thorntail, Quarkus and as an WAR deployment in Wildfly.

== Technologies

* link:https://jdk.java.net/11/[Java JDK 11]
* link:https://docs.jboss.org/wildfly/plugins/maven/2.0.1.Final/[wildfly-maven-plugin]
* link:https://docs.thorntail.io/2.5.0.Final/#using-thorntail-maven-plugin_thorntail[thorntail-maven-plugin]
* link:https://wildfly.org/[Wildfly 18.0.0.Final]
* link:https://github.com/eclipse/microprofile-config/tree/1.3[MicroProfile-Config]
* link:https://github.com/eclipse/microprofile-rest-client/tree/1.3.3[MicroProfile-Rest-Client]
* link:https://github.com/eclipse/microprofile-opentracing/tree/1.3.1[MicroProfile-Opentracing]
* link:https://docs.thorntail.io/2.5.0.Final/[Thorntail]
* link:https://github.com/quarkusio/quarkus/tree/1.0.0.CR1[Quarkus]
* link:https://wildfly.org/[Wildfly 18.0.0.Final]

== Resources

* link:./thorntail-props.yaml[``./thorntail-props.yaml``] +
   The Thorntail configuration file which defines the rest client configuration properties
* link:./src/main/resources/application.properties[``./src/main/resources/application.properties``] +
   The Quarkus configuration file which defines the rest client configuration properties
* link:./src/main/resources/project-defaults.yaml[``./src/main/resources/project-defaults.yaml``] +
   The Thorntail default configuration file.
* link:./wildfly.properties[``./wildfly.properties``] +
   The properties file which defines the rest client configuration properties
* link:./src/main/java/at/ihet/samples/microprofile/opentracing/ExternalRestResource.java[``./src/main/java/at/ihet/samples/microprofile/opentracing/ExternalRestResource.java``] +
   The type safe rest client interface for the external rest resources
* link:./src/main/java/at/ihet/samples/microprofile/opentracing/RestResource.java[``./src/main/java/at/ihet/samples/microprofile/opentracing/RestResource.java``] +
   The rest resource which uses the injectable ExternalResource instance which uses the ClientTracingFeature without modifications
* link:./src/main/java/at/ihet/samples/microprofile/opentracing/CustomRestResource.java[``./src/main/java/at/ihet/samples/microprofile/opentracing/CustomRestResource.java``] +
   The rest resource which builds the ExternalResource instance via the builder and which uses a custom built ClientTracingFeature which uses the ClientSpanDecorator
* link:./src/main/java/at/ihet/samples/microprofile/opentracing/ClientSpanDecorator.java[``./src/main/java/at/ihet/samples/microprofile/opentracing/ClientSpanDecorator.java``] +
   The client side span decorator which adds additional information on the span
* link:./src/main/java/at/ihet/samples/microprofile/opentracing/ServerSpanDecorator.java[``./src/main/java/at/ihet/samples/microprofile/opentracing/ServerSpanDecorator.java``] +
   The server side span decorator which adds additional information on the span
* link:./src/main/java/at/ihet/samples/microprofile/opentracing/TracerFactory.java[``./src/main/java/at/ihet/samples/microprofile/opentracing/TracerFactory.java``] +
   The tracer factory which creates the tracer and registers it on the GlobalTracer
* link:./src/main/java/at/ihet/samples/microprofile/opentracing/TracingInitializerFeature.java[``./src/main/java/at/ihet/samples/microprofile/opentracing/TracingInitializerFeature.java``] +
   The JAX-RS dynamic feature which uses the ServerSpanDecorator

* link:./pom.xml[``./pom.xml``] +
   The ``pom.xml`` defining the Thorntail, Quarkus and Wildfly configurations separated by profiles

== How to build

.Thorntail microservice
[source,bash]
----
mvn clean install -Pthorntail
----

.Quarkus microservice
[source,bash]
----
mvn clean install -Pquarkus
----

.Wildfly WAR deployment
[source,bash]
----
mvn clean install -Pwildfly
----

== How to run

.Start Thorntail microservice
[source,bash]
----
mvn thorntail:run -Pthorntail
----

.Start Quarkus microservice
[source,bash]
----
java "-Djava.net.preferIPv4Stack=true" -jar target\microprofile-opentracing-0.0.1-SNAPSHOT-runner.jar
----

TIP: Normally the maven goal ``quarkus:dev`` should start the application as well but it fails with ClassNotFoundException (org/jboss/logging/Logger). +
     I'm not familiar with Qurakus yet, so we run the jar instead.

.Start/Configure/Deploy Wildfly
[source,bash]
----
mvn wildfly:run -Pwildfly
----


== Prepare test

This sample application requires a Jaeger instance running on ``localhost:6831`` where the traces are sent.

.Start Jaeger with docker
[source,bash]
----
docker run -p 6831:6831/udp -p 16686:16686 --name jaeger-local jaegertracing/all-in-one:latest
----

== How to test

If you use Intellij then you can use the ``test.http`` file for testing the rest endpoints. +
Otherwise see the following available endpoints and use the tool of your choice.

=== With injectable rest client
.GET call to external resource
``GET http://127.0.0.1:8080/get``

.POST call to external resource
``POST http://127.0.0.1:8080/post``

.PATCH call to external resource
``PATCH http://127.0.0.1:8080/patch``

.DELETE call to external resource
``DELETE http://127.0.0.1:8080/delete``


=== With custom built rest client
.GET call to external resource
``GET http://127.0.0.1:8080/custom/get``

.POST call to external resource
``POST http://127.0.0.1:8080/custom/post``

.PATCH call to external resource
``PATCH http://127.0.0.1:8080/custom/patch``

.DELETE call to external resource
``DELETE http://127.0.0.1:8080/custom/delete``

